name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15
    
    strategy:
      matrix:
        include:
          - platform: iOS
            destination: "platform=iOS Simulator,OS=18.5,name=iPhone 16"
            target: "VolleyballController"
          - platform: watchOS
            destination: "platform=watchOS Simulator,OS:11.5,name=Apple Watch SE (40mm) (2nd generation)"
            target: "VolleyballController Watch App"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show available Xcode versions
      shell: bash
      run: |
        echo "::group::Installed Xcodes"
        echo "Current active → $(xcode-select -p)"
        for xc in /Applications/Xcode*.app; do
          # Read the human-readable version from Info.plist
          ver=$(defaults read "$xc/Contents/Info.plist" CFBundleShortVersionString 2>/dev/null)
          echo "• $(basename "$xc") — $ver"
        done
        echo "::endgroup::"

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    
    - name: Show Xcode Version
      run: xcodebuild -version
    
    - name: Build ${{ matrix.platform }} App
      run: |
        xcodebuild clean build \
          -project VolleyballController.xcodeproj \
          -scheme "${{ matrix.target }}" \
          -destination "${{ matrix.destination }}" \
          CODE_SIGNING_ALLOWED=NO
    
    # Only run tests for iOS for now since watchOS tests might have issues
    - name: Test ${{ matrix.platform }} App
      if: matrix.platform == 'iOS'
      run: |
        xcodebuild test \
          -project VolleyballController.xcodeproj \
          -scheme "${{ matrix.target }}" \
          -destination "${{ matrix.destination }}" \
          CODE_SIGNING_ALLOWED=NO

  lint:
    name: SwiftLint
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging