name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15
    
    strategy:
      matrix:
        include:
          - platform: iOS
            destination: "platform=iOS Simulator,name=iPhone 16,OS=18.5"
            target: "VolleyballController"
          - platform: watchOS
            destination: "platform=watchOS Simulator,name=Apple Watch SE (40mm) (2nd generation),arch=arm64"
            target: "VolleyballController Watch App"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Show Xcode Version
      run: xcodebuild -version
    
    - name: Show Available Simulators
      run: xcrun simctl list devices available
    
    - name: Build ${{ matrix.platform }} App
      run: |
        xcodebuild clean build \
          -project VolleyballController.xcodeproj \
          -scheme "${{ matrix.target }}" \
          -destination "${{ matrix.destination }}" \
          CODE_SIGNING_ALLOWED=NO
    
    # Only run tests for iOS for now since watchOS tests might have issues
    - name: Test ${{ matrix.platform }} App
      if: matrix.platform == 'iOS'
      run: |
        xcodebuild test \
          -project VolleyballController.xcodeproj \
          -scheme "${{ matrix.target }}" \
          -destination "${{ matrix.destination }}" \
          CODE_SIGNING_ALLOWED=NO

  lint:
    name: SwiftLint
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging